### ISSUE TITLE
Standardize the inclusion of “distractor objects” & “occluder objects”

### ISSUE THREAD

**Issue by felixbinder** [neuroailab/tdw_physics#40]
ACTION: For each controller, across ALL trials:
Consistently include mix of distractor/occluder objects that do not physically participate but provide visual variability. (Note: these won’t require custom texturization).

**Comment by felixbinder** [comment]
This is what I've been using:
--num_occluders
1
--occluder
full
--occluder_categories "coffee table,cocktail table,houseplant,vase,chair,dog,sculpture,sofa,table,flowerpot,coffee maker,stool,laptop,laptop computer,throw pillow,globe,basket,bookshelf,desktop computer,garden plant,garden plant,garden plant,garden plant,garden plant"
--num_distractors
1
--distractor 
full
--distractor_categories
 "coffee table,cocktail table,houseplant,vase,chair,dog,sculpture,sofa,table,flowerpot,coffee maker,stool,laptop,laptop computer,throw pillow,globe,basket,bookshelf,desktop computer,garden plant,garden plant,garden plant"

**Comment by felixbinder** [comment]
Works fine with 1 each, 2 often leads to clipping.

**Comment by felixbinder** [comment]
Some objects get initialized in an unstable position

**Comment by danielbear** [comment]
@felixbinder @choldawa (and Sirui, don't know his github id): Can you create global variables in your controllers that get passed as defaults to `--occluder_categories` and `--distractor_categories`? This is probably easiest. e.g. 

```
OCCLUDER_CATS = "dog,chair,..."
DISTRACTOR_CATS = "coffee machine,table,..."
...

parser.add_argument("--occluder_categories,
                                      type=none_or_str,
                                      default=OCCLUDER_CATS,
                                      help="the category ids to sample occluders from")
```

**Comment by felixbinder** [comment]
The full code is
```
OCCLUDER_CATS = "coffee table,houseplant,vase,chair,dog,sofa,flowerpot,coffee maker,stool,laptop,laptop computer,globe,bookshelf,desktop computer,garden plant,garden plant,garden plant"
DISTRACTOR_CATS = "coffee table,houseplant,vase,chair,dog,sofa,flowerpot,coffee maker,stool,laptop,laptop computer,globe,bookshelf,desktop computer,garden plant,garden plant,garden plant"
```
and
```
    ### occluder/distractors
    parser.add_argument("--occluder_categories",
                                      type=none_or_str,
                                      default=OCCLUDER_CATS,
                                      help="the category ids to sample occluders from")
    parser.add_argument("--distractor_categories",
                                      type=none_or_str,
                                      default=DISTRACTOR_CATS,
                                      help="the category ids to sample distractors from")
```
