### ISSUE TITLE
Send boxes, send meshes

### ISSUE THREAD

**Issue by danielbear** [neuroailab/tdw_physics#44]
Make sure the build is sending the TDW bounding boxes (and meshes?) during stim generation

**Comment by htung0101** [comment]
I have added this to my branch, please search for the key word "save_meshes"

https://github.com/neuroailab/tdw_physics/blob/htung_render/tdw_physics/dataset.py
https://github.com/neuroailab/tdw_physics/blob/htung_render/tdw_physics/target_controllers/dominoes.py#L1753

**Comment by danielbear** [comment]
now bounding boxes (3D) sent automatically and saved in hdf5: 

```
bounds = [data['frames']['objects'][bound_type] for bound_type in ['top', 'right', 'left', 'bottom', 'center', ...]]
```

@htung0101 can you merge in your meshes saving when ready? I added `--save_meshes` as a general flag to the scripts, but don't want to duplicate your work on actually saving the meshes.
