### ISSUE TITLE
Important bug in saved objects' ordering

### ISSUE THREAD

**Issue by htung0101** [neuroailab/tdw_physics#47]
I found that the order of the object is sometimes mismatched in self.object_ids, self.model_names/self.scales/self.colors.
ex. The probe ball size is swaped with the the ramp
![Screenshot from 2021-04-26 15-44-18](https://user-images.githubusercontent.com/6644116/116141838-368ea780-a6a7-11eb-853c-83c6e4b6472d.png)

I researched a bit and the thing that is causing the problem is this:
https://github.com/neuroailab/tdw_physics/blob/master/tdw_physics/target_controllers/dominoes.py#L1063

When you add an object, there are two different steps: (1) build the basic info the object and add if to self.object_ids (2) append it to self.colors, self.scales, self.model_names.
Currently, the function is doing: 
1. do (1) for probe 
2. do (1)(2) for ramp with self._place_ramp_under_prob()
3. do (2) for probe

in this case, object_ids will using the order of [probe, ramp], while self.scales will be using the order [ramp, probe].
So they are not consistent. 

The fix is to move
```
        if self.use_ramp:
            commands.extend(self._place_ramp_under_probe())
```
after you do add_physics_objects:  https://github.com/neuroailab/tdw_physics/blob/master/tdw_physics/target_controllers/dominoes.py#L1067

After this, it is correct:
![Screenshot from 2021-04-26 15-54-39](https://user-images.githubusercontent.com/6644116/116142728-41960780-a6a8-11eb-86ea-4c66674fe243.png)

**Comment by danielbear** [comment]
Resolved by one of the commits merged in with the `flex` branch. Now scales, colors, model_names are in the same order as the object_ids by handling the add_data for ramp as a special case.

**Comment by danielbear** [comment]
Issue in rollingsliding with ramp
