### ISSUE TITLE
Produce collision labels for cloth-objects with other flex objects

### ISSUE THREAD

**Issue by arty-p** [neuroailab/tdw_physics#48]

**Comment by danielbear** [comment]
Unfortunately, TDW's mesh colliders don't work for FLEX-based cloth objects and so can't tell whether a cloth collided with another object.

@htung0101 in your DPI model readout, do you have a function that is checking whether two FLEX-particalized objects are colliding? For instance (in pseudocode):

```
def are_obj1_obj2_colliding(f, frame_id, obj1_id, obj2_id):
     particles1 = f['frames'][frame_id]['objects'][obj1_id]['particles']
     particles2 = f['frames'][frame_id]['objects'][obj2_id]['particles']
     colliding = False
     for p1 in particles1: 
          for p2 in particles2:
               if L2_distance(p1, p2) < thresh:
                   colliding = True
     return colliding
```

Of course you may have written a better/faster version of this. If so, could you point me to it so we can generate "does target hit zone" labels for the FLEX controllers with Cloth?
