### ISSUE TITLE
Mesh with no vertex

### ISSUE THREAD

**Issue by htung0101** [neuroailab/tdw_physics#53]
After using the flag `--only_use_flex_objects` to exclude non flex objects, I still find some objects to have zero vertex.
In particular, "'648972_chair_poliform_harmony'" under the category "chair".

I will try to add a filter on my side. But I feel we should ask Seth and Jeremy to change the label for this object.

**Comment by danielbear** [comment]
If you try `python util.py --flex --model_category "chair"`, does this model_name show up as being flex-enabled?
